# Generated by Django 6.0.4 on 2026-05-08 21:13

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20260507_1355"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="internshipoffer",
            name="offer_creation_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="internshipoffer",
            name="offer_end_date",
            field=models.DateField(default=datetime.date(2026, 6, 7)),
        ),
        migrations.AlterField(
            model_name="internshipoffer",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.city"
            ),
        ),
    ]
