# Generated by Django 6.0.4 on 2026-04-28 04:42


def populate_cities(apps, schema_editor):
    City = apps.get_model('accounts', 'City')
    Location = apps.get_model('accounts', 'Location')


    data_map = {
        "Cairo": ("Mokattam", "Manial", "Madinaty", "Salam City", "Badr City", "New Nozha", "Bab Alshareya", "Sharabeya", "10th of Ramadan City", "Azbakia", "Katameya", "Helmeyat Alzaytoun", "Downtown", "15th May City", "Marg", "Rehab City", "Basatin", "Obour City", "Zamalek", "Heliopolis", "New Capital", "Sayeda Zeinab", "Nozha", "Shorouk City", "Abdeen", "Helwan", "Nasr City", "Maadi", "Sheraton", "Garden City", "Abbassia", "New Cairo", "Ain Shams", "Shubra", "New Heliopolis"),
        "Giza": ("Mohandessin", "Imbaba", "Sheikh Zayed", "Hadayek October", "Agouza", "Abu Rawash", "Giza", "Smart Village", "Haram", "6th of October", "Dokki", "Faisal", "Hadayek Alahram"),
        "Sharqia": ("Belbes", "10th of Ramadan City", "Zagazig"),
        "Alexandria": ("Alhadra", "Moharam Bek", "Mansheya", "San Stefano", "Allabban", "Agami", "Bourj Alarab", "Gomrok", "Fleming", "Attarin", "Mahta Alraml", "Bab Sharq", "Sidi Gaber", "Victoria", "Bolkly", "Siouf", "Azarita", "Smouha", "Sidi Bishr", "Stanley", "Mandara", "Montaza", "Glim", "Ameria"),
        "Gharbia": ("Tanta", "Mahalla Kubra", "Santah", "Kafr Alzayat"),
        "Assiut": ("Assuit", "New Assuit"),
        "Dakahlia": ("Aga", "Mit Ghamr", "Mansoura"),
        "Monufya": ("Shebin Alkom", "Quweisna", "Alsadat City"),
        "Matruh": ("Marsa Matruh", "Siwa Oasis"),
        "Damietta": ("Damietta", "New Damietta"),
        "Red Sea": ("Ras Ghareb", "Hurghada"),
        "New Valley": ("Farafra",),
        "Minya": ("Mallawi", "New Menia", "Menia"),
        "Beni Suef": ("Beni Suef"),
        "Beheira": ("Noubaria", "Damanhour", "Abu Almatamir", "Wadi Alnatrun"),
        "Suez": ("Ain Sokhna", "Ataqah", "Suez"),
        "Qalubia": ("Banha", "khanka", "Qalyub"),
        "Aswan": ("Aswan", "Adfo"),
        "Fayoum": ("Fayoum", "Itsa"),
        "South Sinai": ("Ras Sedr", "Sharm Alsheikh", "Dahab"),
        "Ismailia": ("Ismailia", "Qantarah Sharq"),
        "Qena": ("Qena"),
    }

    for country_name, locations in data_map.items():
        city_obj, _ = City.objects.get_or_create(name=country_name)
        for loc_name in locations:
            Location.objects.get_or_create(name=loc_name, city=city_obj)

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'), # Make sure this matches your last migration
    ]

    operations = [
        migrations.RunPython(populate_cities),
    ]
