# Generated by Django 6.0.4 on 2026-04-29 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_addresses_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="account_creation_date",
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_id",
        ),
        migrations.RemoveField(
            model_name="company",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="account_creation_date",
        ),
        migrations.AddField(
            model_name="company",
            name="company_created_at",
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.city"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.location"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="company",
            name="market_share",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="company",
            name="password",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="company",
            name="website_url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="accounts.city",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="user",
            name="second_name",
            field=models.CharField(max_length=50),
        ),
    ]
