# Generated by Django 6.0.4 on 2026-04-29 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_company_account_creation_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.city",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.location",
            ),
        ),
    ]
