# Generated by Django 6.0.4 on 2026-04-29 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_company_city_company_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.city"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.location"
            ),
        ),
    ]
